# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33c8e344afc5877aa6323b809a6388b6173ded7a85d0960dfe47939b178d56e1a79f6bdce7aad2bb8f1f3e16b0a68a7e6b899c3ca6230bb3e6cf7a7ff29d1c1b

test:
  secret_key_base: e4cb4fcb17f3ca2aa36552e8cd08b491eaa3b2a5655ac77f2792005d5f3ea3333f8b0d560b7cc2862932d3f5e9cd31536db66eb012542dd7bbfd244fcd11a567

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
